import Head from "next/head";
import React, { Fragment, ReactNode, useState } from "react";
import Footer from "./Footer";
import Header from "./Header";
import Sidebar from "./Sidebar";

type Props = {
    children: ReactNode,
    title:string
  }
const Layout = ({children, title="Sample Title"}:Props) => {
     const [mobileNavsidebar, setMobileNavsidebar] = useState(false);
     


  return (
    <Fragment>
      
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>

       <div className="flex bg-gray-100 min-h-screen relative">
        
          <Sidebar mobileNavsidebar={mobileNavsidebar} />
          
          <div className="flex-grow text-gray-800">
          <Header mobileNavsidebar={mobileNavsidebar} setMobileNavsidebar={setMobileNavsidebar} />
              {children}
          </div>

        <Footer />
      </div> 
        

    </Fragment>
  );
};

export default Layout;
